### ISSUE TITLE
Lat/Lng

### ISSUE THREAD

**Issue by matrox66** [leegarner-glfusion/locator#2]
If you create a Location you can enter Lat/Lng like 45.324526 | 15.356692
If you update the Location - Lat/Lng will Change from Point to comma
45.324526 | 15.356692 will Change to 45,324526 | 15,356692
if you save the entry and update again everything behind the comma will lost
45,324526 | 15,356692 will Change to 45 | 15

**Comment by leegarner** [comment]
Fixed by replacing commas with periods internally
